import 'models.dart';

const List<JigsawCategoryData> jigsawCategories = [
  JigsawCategoryData(
    id: 'animals',
    name: 'Hayvonlar',
    emoji: '🐾',
    gradientColors: ['FFB8E0FF', 'FF88D8C8'],
    levels: [
      JigsawLevelData(id: 'pandas', name: 'Pandalar', imagePath: 'assets/jigsaw/webp/animals/pandas.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'space_kitten', name: 'Kosmik Mushuk', imagePath: 'assets/jigsaw/webp/animals/space_kitten.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'fox', name: 'Tulki', imagePath: 'assets/jigsaw/webp/animals/fox.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'penguin', name: 'Pingvinlar', imagePath: 'assets/jigsaw/webp/animals/penguin.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'lion_cub', name: 'Sher Bolasi', imagePath: 'assets/jigsaw/webp/animals/lion_cub.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'rabbit', name: 'Quyon', imagePath: 'assets/jigsaw/webp/animals/rabbit.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'elephant', name: 'Fil', imagePath: 'assets/jigsaw/webp/animals/elephant.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'giraffe', name: 'Jirafa', imagePath: 'assets/jigsaw/webp/animals/giraffe.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'koala', name: 'Koala', imagePath: 'assets/jigsaw/webp/animals/koala.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'hamster', name: 'Hamster', imagePath: 'assets/jigsaw/webp/animals/hamster.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'cat_window', name: 'Mushukcha', imagePath: 'assets/jigsaw/webp/animals/cat_window.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'pony', name: 'Poni', imagePath: 'assets/jigsaw/webp/animals/pony.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'hedgehog', name: 'Tipratikon', imagePath: 'assets/jigsaw/webp/animals/hedgehog.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'red_panda', name: 'Qizil Panda', imagePath: 'assets/jigsaw/webp/animals/red_panda.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'squirrel', name: 'Olmaxon', imagePath: 'assets/jigsaw/webp/animals/squirrel.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'baby_deer', name: 'Kiyik Bolasi', imagePath: 'assets/jigsaw/webp/animals/baby_deer.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'polar_bear', name: 'Oq Ayiq', imagePath: 'assets/jigsaw/webp/animals/polar_bear.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'raccoon', name: 'Yenot', imagePath: 'assets/jigsaw/webp/animals/raccoon.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'chameleon', name: 'Xameleon', imagePath: 'assets/jigsaw/webp/animals/chameleon.webp', category: 'animals', isUnlocked: true),
      JigsawLevelData(id: 'wolf', name: "Bo'ri", imagePath: 'assets/jigsaw/webp/animals/wolf.webp', category: 'animals', isUnlocked: true),
    ],
  ),
  JigsawCategoryData(
    id: 'birds',
    name: 'Qushlar',
    emoji: '🦜',
    gradientColors: ['FFFFD6A0', 'FFFF9A6C'],
    levels: [
      JigsawLevelData(id: 'parrot', name: "To'ti", imagePath: 'assets/jigsaw/webp/birds/parrot.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'owls', name: 'Boyqushlar', imagePath: 'assets/jigsaw/webp/birds/owls.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'flamingos', name: 'Flamingolar', imagePath: 'assets/jigsaw/webp/birds/flamingos.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'eagle', name: 'Burgut', imagePath: 'assets/jigsaw/webp/birds/eagle.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'toucan', name: 'Tukan', imagePath: 'assets/jigsaw/webp/birds/toucan.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'peacock', name: 'Tovus', imagePath: 'assets/jigsaw/webp/birds/peacock.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'hummingbird', name: 'Kolibri', imagePath: 'assets/jigsaw/webp/birds/hummingbird.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'kingfisher', name: 'Baliqchi', imagePath: 'assets/jigsaw/webp/birds/kingfisher.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'swan', name: "Oqqush", imagePath: 'assets/jigsaw/webp/birds/swan.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'robin', name: "Zug'ich", imagePath: 'assets/jigsaw/webp/birds/robin.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'pelican', name: 'Pelikan', imagePath: 'assets/jigsaw/webp/birds/pelican.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'woodpecker', name: "To'qildog'on", imagePath: 'assets/jigsaw/webp/birds/woodpecker.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'stork', name: 'Laylak', imagePath: 'assets/jigsaw/webp/birds/stork.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'macaw', name: 'Makao', imagePath: 'assets/jigsaw/webp/birds/macaw.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'kingfisher_dive', name: "Sho'ng'igan Baliqchi", imagePath: 'assets/jigsaw/webp/birds/kingfisher_dive.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'snowy_owl', name: 'Qor Boyqush', imagePath: 'assets/jigsaw/webp/birds/snowy_owl.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'heron', name: "Ko'kqush", imagePath: 'assets/jigsaw/webp/birds/heron.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'blue_jay', name: "Ko'k Jay", imagePath: 'assets/jigsaw/webp/birds/blue_jay.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'cardinal', name: 'Kardinal', imagePath: 'assets/jigsaw/webp/birds/cardinal.webp', category: 'birds', isUnlocked: true),
      JigsawLevelData(id: 'crane', name: 'Turna', imagePath: 'assets/jigsaw/webp/birds/crane.webp', category: 'birds', isUnlocked: true),
    ],
  ),
  JigsawCategoryData(
    id: 'nature',
    name: 'Tabiat',
    emoji: '🌿',
    gradientColors: ['FFC8E8FF', 'FFFFD580'],
    levels: [
      JigsawLevelData(id: 'waterfall', name: 'Sharshara', imagePath: 'assets/jigsaw/webp/nature/waterfall.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'winter_village', name: 'Qishki Qishloq', imagePath: 'assets/jigsaw/webp/nature/winter_village.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'autumn_forest', name: "Kuzgi O'rmon", imagePath: 'assets/jigsaw/webp/nature/autumn_forest.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'sakura', name: 'Sakura Bog', imagePath: 'assets/jigsaw/webp/nature/sakura.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'volcano', name: 'Vulqon', imagePath: 'assets/jigsaw/webp/nature/volcano.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'rainbow_valley', name: 'Kamalak Vodiysi', imagePath: 'assets/jigsaw/webp/nature/rainbow_valley.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'mountain_lake', name: "Tog' Ko'li", imagePath: 'assets/jigsaw/webp/nature/mountain_lake.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'sunset_beach', name: 'Quyosh Botishi', imagePath: 'assets/jigsaw/webp/nature/sunset_beach.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'northern_lights', name: "Shimol Yog'dusi", imagePath: 'assets/jigsaw/webp/nature/northern_lights.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'mushroom_forest', name: "Qo'ziqorin O'rmoni", imagePath: 'assets/jigsaw/webp/nature/mushroom_forest.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'tropical_island', name: 'Tropik Orol', imagePath: 'assets/jigsaw/webp/nature/tropical_island.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'lavender_field', name: 'Lavanda Dalasi', imagePath: 'assets/jigsaw/webp/nature/lavender_field.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'cherry_river', name: 'Sakura Daryosi', imagePath: 'assets/jigsaw/webp/nature/cherry_river.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'crystal_cave', name: "Kristal G'or", imagePath: 'assets/jigsaw/webp/nature/crystal_cave.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'desert_oasis', name: 'Sahro Vodiyligi', imagePath: 'assets/jigsaw/webp/nature/desert_oasis.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'bamboo_forest', name: "Bambuk O'rmoni", imagePath: 'assets/jigsaw/webp/nature/bamboo_forest.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'aurora_mountains', name: "Aurora Tog'lari", imagePath: 'assets/jigsaw/webp/nature/aurora_mountains.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'coral_reef', name: 'Marjon Rifi', imagePath: 'assets/jigsaw/webp/nature/coral_reef.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'floating_islands', name: 'Suzuvchi Orollar', imagePath: 'assets/jigsaw/webp/nature/floating_islands.webp', category: 'nature', isUnlocked: true),
      JigsawLevelData(id: 'glacier_lake', name: "Muzlik Ko'l", imagePath: 'assets/jigsaw/webp/nature/glacier_lake.webp', category: 'nature', isUnlocked: true),
    ],
  ),
  JigsawCategoryData(
    id: 'fantasy',
    name: 'Sehrli Jonzotlar',
    emoji: '🐲',
    gradientColors: ['FFD0BFFF', 'FFFFA8E8'],
    levels: [
      JigsawLevelData(id: 'dragon', name: 'Ajdaho', imagePath: 'assets/jigsaw/webp/fantasy/dragon.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'unicorn', name: 'Yagana Shoxli Ot', imagePath: 'assets/jigsaw/webp/fantasy/unicorn.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'phoenix', name: 'Feniks', imagePath: 'assets/jigsaw/webp/fantasy/phoenix.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'fairy', name: 'Pari', imagePath: 'assets/jigsaw/webp/fantasy/fairy.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'griffin', name: 'Griffin', imagePath: 'assets/jigsaw/webp/fantasy/griffin.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'mermaid', name: 'Suv Parisi', imagePath: 'assets/jigsaw/webp/fantasy/mermaid.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'magic_castle', name: 'Sehrli Qasr', imagePath: 'assets/jigsaw/webp/fantasy/magic_castle.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'wizard', name: 'Sehrgar', imagePath: 'assets/jigsaw/webp/fantasy/wizard.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'pegasus', name: 'Pegas', imagePath: 'assets/jigsaw/webp/fantasy/pegasus.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'elf_forest', name: 'Elf Dunyosi', imagePath: 'assets/jigsaw/webp/fantasy/elf_forest.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'ice_queen', name: 'Muz Malikasi', imagePath: 'assets/jigsaw/webp/fantasy/ice_queen.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'treasure_cave', name: "Xazina G'ori", imagePath: 'assets/jigsaw/webp/fantasy/treasure_cave.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'candy_castle', name: 'Shirinlik Qasri', imagePath: 'assets/jigsaw/webp/fantasy/candy_castle.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'forest_spirit', name: "O'rmon Ruhi", imagePath: 'assets/jigsaw/webp/fantasy/forest_spirit.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'cloud_kingdom', name: 'Bulut Qirolligi', imagePath: 'assets/jigsaw/webp/fantasy/cloud_kingdom.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'mushroom_fairy', name: "Qo'ziqorin Pari", imagePath: 'assets/jigsaw/webp/fantasy/mushroom_fairy.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'flying_dragon', name: 'Uchuvchi Ajdaho', imagePath: 'assets/jigsaw/webp/fantasy/flying_dragon.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'magic_tree', name: 'Sehrli Daraxt', imagePath: 'assets/jigsaw/webp/fantasy/magic_tree.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'crystal_dragon', name: 'Kristal Ajdaho', imagePath: 'assets/jigsaw/webp/fantasy/crystal_dragon.webp', category: 'fantasy', isUnlocked: true),
      JigsawLevelData(id: 'witch_garden', name: 'Jodugar Bog', imagePath: 'assets/jigsaw/webp/fantasy/witch_garden.webp', category: 'fantasy', isUnlocked: true),
    ],
  ),
  JigsawCategoryData(
    id: 'aquatic',
    name: 'Suv Jonzotlari',
    emoji: '🐬',
    gradientColors: ['FF80D0FF', 'FF40A8D8'],
    levels: [
      JigsawLevelData(id: 'dolphin', name: 'Delfin', imagePath: 'assets/jigsaw/webp/aquatic/dolphin.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'jellyfish', name: 'Meduza', imagePath: 'assets/jigsaw/webp/aquatic/jellyfish.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'octopus', name: 'Sakkiz Oyoq', imagePath: 'assets/jigsaw/webp/aquatic/octopus.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'whale', name: 'Kit', imagePath: 'assets/jigsaw/webp/aquatic/whale.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'seahorse', name: 'Dengiz Oti', imagePath: 'assets/jigsaw/webp/aquatic/seahorse.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'clownfish', name: 'Masxara Baliq', imagePath: 'assets/jigsaw/webp/aquatic/clownfish.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'sea_crab', name: 'Qisqichbaqa', imagePath: 'assets/jigsaw/webp/aquatic/sea_crab.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'sea_turtle', name: 'Toshbaqa', imagePath: 'assets/jigsaw/webp/aquatic/sea_turtle.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'stingray', name: 'Skat Baliq', imagePath: 'assets/jigsaw/webp/aquatic/stingray.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'pufferfish', name: 'Shishak Baliq', imagePath: 'assets/jigsaw/webp/aquatic/pufferfish.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'narwhal', name: 'Narval', imagePath: 'assets/jigsaw/webp/aquatic/narwhal.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'lobster', name: 'Omar', imagePath: 'assets/jigsaw/webp/aquatic/lobster.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'manta_ray', name: 'Manta', imagePath: 'assets/jigsaw/webp/aquatic/manta_ray.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'sea_otter', name: 'Dengiz Samuri', imagePath: 'assets/jigsaw/webp/aquatic/sea_otter.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'coral_garden', name: 'Marjon Bog', imagePath: 'assets/jigsaw/webp/aquatic/coral_garden.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'baby_seal', name: 'Tyulen Bolasi', imagePath: 'assets/jigsaw/webp/aquatic/baby_seal.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'tropical_fish', name: 'Tropik Baliqlar', imagePath: 'assets/jigsaw/webp/aquatic/tropical_fish.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'penguin_family', name: 'Pingvin Oilasi', imagePath: 'assets/jigsaw/webp/aquatic/penguin_family.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'axolotl', name: 'Aksolotl', imagePath: 'assets/jigsaw/webp/aquatic/axolotl.webp', category: 'aquatic', isUnlocked: true),
      JigsawLevelData(id: 'hammerhead', name: "Bolg'a Baliq", imagePath: 'assets/jigsaw/webp/aquatic/hammerhead.webp', category: 'aquatic', isUnlocked: true),
    ],
  ),
];
